#!/bin/bash
##############################################################################
# ESGF wget download script
#
# Template version: 0.4
# Generated by metagrid.esgf-west.org - 2026/09/02 09:24:39
# Search URL: http://metagrid.esgf-west.org/proxy/wget
# Request method: POST
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############"
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=0.4
CACHE_FILE=.$(basename $0).status
search_url='http://metagrid.esgf-west.org/proxy/wget'
request_method='POST'
url_params=(
    '[&#x27;CMIP6.CMIP.NCAR.CESM2-WACCM.historical.r3i1p1f1.day.pr.gn.v20190415|esgf-node.ornl.gov&#x27;]'
)

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'pr_day_CESM2-WACCM_historical_r3i1p1f1_gn_18800101-18891231.nc' 'http://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/NCAR/CESM2-WACCM/historical/r3i1p1f1/day/pr/gn/v20190415/pr_day_CESM2-WACCM_historical_r3i1p1f1_gn_18800101-18891231.nc' 'SHA256' '42bbd84b25e2a08aadd83f9c219fbd2488203ae012a40690c1d7f8fab289e137'
'pr_day_CESM2-WACCM_historical_r3i1p1f1_gn_19300101-19391231.nc' 'http://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/NCAR/CESM2-WACCM/historical/r3i1p1f1/day/pr/gn/v20190415/pr_day_CESM2-WACCM_historical_r3i1p1f1_gn_19300101-19391231.nc' 'SHA256' '30ae786e9ac0d20d0e508482a51be3c4b5fbe0632bb7a80232467af88d333518'
'pr_day_CESM2-WACCM_historical_r3i1p1f1_gn_19500101-19591231.nc' 'http://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/NCAR/CESM2-WACCM/historical/r3i1p1f1/day/pr/gn/v20190415/pr_day_CESM2-WACCM_historical_r3i1p1f1_gn_19500101-19591231.nc' 'SHA256' 'eb5f2b94013551875281ed8e357a9693d72ffc3c5b41c100724897a88dae04d8'
'pr_day_CESM2-WACCM_historical_r3i1p1f1_gn_18700101-18791231.nc' 'http://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/NCAR/CESM2-WACCM/historical/r3i1p1f1/day/pr/gn/v20190415/pr_day_CESM2-WACCM_historical_r3i1p1f1_gn_18700101-18791231.nc' 'SHA256' '047515ecc222d8804e6f99582b609f5889ed0dca0b55c04ff520d5d340f8f0f4'
'pr_day_CESM2-WACCM_historical_r3i1p1f1_gn_18900101-18991231.nc' 'http://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/NCAR/CESM2-WACCM/historical/r3i1p1f1/day/pr/gn/v20190415/pr_day_CESM2-WACCM_historical_r3i1p1f1_gn_18900101-18991231.nc' 'SHA256' 'bd24f37a61087b066de70148c6c19a0b0d541027469ebd2a1df289e009f5b62d'
'pr_day_CESM2-WACCM_historical_r3i1p1f1_gn_19000101-19091231.nc' 'http://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/NCAR/CESM2-WACCM/historical/r3i1p1f1/day/pr/gn/v20190415/pr_day_CESM2-WACCM_historical_r3i1p1f1_gn_19000101-19091231.nc' 'SHA256' '7baa524c8a64eb87b35e0e0ef429ecb818040e47a31cdfead4d4978db79d882b'
'pr_day_CESM2-WACCM_historical_r3i1p1f1_gn_19900101-19991231.nc' 'http://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/NCAR/CESM2-WACCM/historical/r3i1p1f1/day/pr/gn/v20190415/pr_day_CESM2-WACCM_historical_r3i1p1f1_gn_19900101-19991231.nc' 'SHA256' 'd4ab0ee93470ff3a682718a86336d7ddca78d0b1c4f5185ba77569813520da7e'
'pr_day_CESM2-WACCM_historical_r3i1p1f1_gn_19100101-19191231.nc' 'http://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/NCAR/CESM2-WACCM/historical/r3i1p1f1/day/pr/gn/v20190415/pr_day_CESM2-WACCM_historical_r3i1p1f1_gn_19100101-19191231.nc' 'SHA256' '44280a83c753575f25d8f6ae7b8a6d529ea44a587ccb4ece7fb204f88262c6b6'
'pr_day_CESM2-WACCM_historical_r3i1p1f1_gn_18600101-18691231.nc' 'http://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/NCAR/CESM2-WACCM/historical/r3i1p1f1/day/pr/gn/v20190415/pr_day_CESM2-WACCM_historical_r3i1p1f1_gn_18600101-18691231.nc' 'SHA256' '560d39be76cf1c6f9061532855297572c2bd8730b236c8f1f457d580f276bacf'
'pr_day_CESM2-WACCM_historical_r3i1p1f1_gn_19200101-19291231.nc' 'http://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/NCAR/CESM2-WACCM/historical/r3i1p1f1/day/pr/gn/v20190415/pr_day_CESM2-WACCM_historical_r3i1p1f1_gn_19200101-19291231.nc' 'SHA256' '54522f5d0aa4ee206eb709a555087dc44a14ae72679e098f3707f398c9ae7f38'
'pr_day_CESM2-WACCM_historical_r3i1p1f1_gn_19400101-19491231.nc' 'http://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/NCAR/CESM2-WACCM/historical/r3i1p1f1/day/pr/gn/v20190415/pr_day_CESM2-WACCM_historical_r3i1p1f1_gn_19400101-19491231.nc' 'SHA256' '5345290d292be65eaab7a1be80fd400fbfeec8ffa2ae7caeecebd017eca32694'
'pr_day_CESM2-WACCM_historical_r3i1p1f1_gn_19800101-19891231.nc' 'http://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/NCAR/CESM2-WACCM/historical/r3i1p1f1/day/pr/gn/v20190415/pr_day_CESM2-WACCM_historical_r3i1p1f1_gn_19800101-19891231.nc' 'SHA256' '82b2e0c5ceed10bf31ce09a809b1216ed8aa31280a77b12d80f3248963b4f9d6'
'pr_day_CESM2-WACCM_historical_r3i1p1f1_gn_20100101-20150101.nc' 'http://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/NCAR/CESM2-WACCM/historical/r3i1p1f1/day/pr/gn/v20190415/pr_day_CESM2-WACCM_historical_r3i1p1f1_gn_20100101-20150101.nc' 'SHA256' '472481540efbde4d5900dadaf8df6f01ce9d917b616e71e513218dd613b84a25'
'pr_day_CESM2-WACCM_historical_r3i1p1f1_gn_18500101-18591231.nc' 'http://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/NCAR/CESM2-WACCM/historical/r3i1p1f1/day/pr/gn/v20190415/pr_day_CESM2-WACCM_historical_r3i1p1f1_gn_18500101-18591231.nc' 'SHA256' 'c12759df11b9718a2a06be81c216e58c397a5d062e462d3ee7d83e8a8750f2f5'
'pr_day_CESM2-WACCM_historical_r3i1p1f1_gn_19700101-19791231.nc' 'http://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/NCAR/CESM2-WACCM/historical/r3i1p1f1/day/pr/gn/v20190415/pr_day_CESM2-WACCM_historical_r3i1p1f1_gn_19700101-19791231.nc' 'SHA256' '06c1321f4c45b756996a9d6fd36d2f2582ad0a04f3da25cff247af7099a7cb9a'
'pr_day_CESM2-WACCM_historical_r3i1p1f1_gn_19600101-19691231.nc' 'http://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/NCAR/CESM2-WACCM/historical/r3i1p1f1/day/pr/gn/v20190415/pr_day_CESM2-WACCM_historical_r3i1p1f1_gn_19600101-19691231.nc' 'SHA256' '35874b05f553b180428619784df658789080b77fc24bc4303cb20fb3c8635d45'
'pr_day_CESM2-WACCM_historical_r3i1p1f1_gn_20000101-20091231.nc' 'http://esgf-node.ornl.gov/thredds/fileServer/css03_data/CMIP6/CMIP/NCAR/CESM2-WACCM/historical/r3i1p1f1/day/pr/gn/v20190415/pr_day_CESM2-WACCM_historical_r3i1p1f1_gn_20000101-20091231.nc' 'SHA256' '2c6d4aef58e3111d629afacdaa2389a6570e03a2e39b7ec471dbc27f6afd71c1'
EOF--dataset.file.url.chksum_type.chksum
)"

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts 'F:w:iuUnSpdvqh' OPT; do
    case $OPT in
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        S) skip_checksum=1;;            #       : Skip file checksum
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi

#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    post_data=$(IFS="&" ; echo "${url_params[*]}")
    new_wget="$(wget --post-data "$post_data" "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0
fi

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v}"

    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"

        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi

        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have.
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count

        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                $wget -O "$file" $url || { failed=1; break; }
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if ((skip_checksum)); then
                    echo "Skipping check of file checksum"
                    break
                fi
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi

                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done

        if ((failed)); then
            echo "download failed"
            unset failed
        fi

    done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#
# MAIN
#

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

cat <<'EOF-MESSAGE'
Script created for 17 file(s)
(The count won't match if you manually edit this file!)

EOF-MESSAGE
sleep 1

check_os

download

dedup_cache_

echo "done"
